[toolchain]

[features]
resolution = true
skip-lint = false

# [programs.devnet]
[programs.localnet]
blockchain_checkers = "J5zCTZCbJieJ1Wf88ZxACMZyEkVvYpxXQ6nCMULGmLGy"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "http://localhost:8899"

wallet = "./dev-wallet.json"
# wallet = "~/home/mfoniso/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
